### ISSUE TITLE
Include Github badges

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/json-to-go-map#10]
Include Github badges in README.

- [x] Build Travis
- [x] License
- [x] Coverage (Optional)

**Comment by hunthunt2010** [comment]
I'll try my hand at this one :)

**Comment by hunthunt2010** [comment]
@rodrigo-brito is there Coveralls or similar set up for this project that I can grab a coverage badge from?

**Comment by hunthunt2010** [comment]
I ended up starting another branch to add the coverage - assuming you'd need to enable Coveralls for this repo. If you want to use another tool let me know. But Coveralls was easy to setup. 

https://github.com/rodrigo-brito/json-to-go-map/pull/13

**Comment by rodrigo-brito** [comment]
Hi @hunthunt2010, I activated the coveralls in the repository. 
https://coveralls.io/github/rodrigo-brito/json-to-go-map

**Comment by rodrigo-brito** [comment]
The badge markdown is:
```
[![Coverage Status](https://coveralls.io/repos/github/rodrigo-brito/json-to-go-map/badge.svg)](https://coveralls.io/github/rodrigo-brito/json-to-go-map)
```

**Comment by hunthunt2010** [comment]
awesome - thank you for doing that. I've updated my PR
